# Generated by Django 5.0.4 on 2024-05-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescontent',
            name='code',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='articlescontent',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
