# Generated by Django 5.0.4 on 2024-05-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message_count',
            field=models.IntegerField(null=True),
        ),
    ]
