# Generated by Django 5.0.4 on 2024-05-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_message_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
    ]
